spring:
  application:
    name: APPGO
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/appgo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName:
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 10000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000 #连接在连接池的最小生存时间（毫秒）
#  redis:
#    host: 127.0.0.1
#    port: 6379
    #    jedis:
    #      pool:
    #        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8 # 连接池中的最大空闲连接
    #        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3600 # 连接超时时间（毫秒）

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hzh.service.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com.hzh.service.mapper : DEBUG
#    root: DEBUG
#日志配置
#log:
#  path: E:/logs/opark
#  level: info